[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"